---

name: CI

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  Test_Browser_Ubuntu:
    name: Test (${{ matrix.browser }} on ubuntu)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Setup
        run: sudo apt-get install -y xvfb

      - name: Test
        run: |
          xvfb-run --auto-servernum npx testcafe ${{ matrix.browser }}:headless test/browser/**

      - name: Teardown
        if: always()
        run: |
          xvfb_pids=`ps aux | grep tmp/xvfb-run | grep -v grep | awk '{print $2}'`
          if [ "$xvfb_pids" != "" ]; then
            sudo kill $xvfb_pids || true
          fi

      - name: Upload
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ${{ matrix.browser }} on ubuntu
          path: test/screenshots

  Test_Browser_Windows:
    name: Test (${{ matrix.browser }} on windows)
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - edge
          - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci
        shell: powershell

      - name: Test
        run: npx testcafe ${{ matrix.browser }} test/browser/**
        shell: powershell

      - name: Upload
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ${{ matrix.browser }} on windows
          path: test/screenshots

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Lint
      - Test_Browser_Ubuntu
      - Test_Browser_Windows
      - Build

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      # TODO: Actually deploy
